### ISSUE TITLE
negations not defined

### ISSUE THREAD

**Issue by bevankoopman** [Georgetown-IR-Lab/QuickUMLS#2]
I managed to get QuickUMLS setup properly in ubuntu based docker container. 

When I run it, however, it seems that negations is never set and hence an error occurs. Here is my test code:

```python
from quickumls import *

matcher = QuickUMLS('/quick-umls-data')

text = 'The ulna has dislocated posteriorly from the trochlea of the humerus.'
matcher.match(text, best_match=True, ignore_syntax=False)
```

Here is the stack trace when I run `python test_matcher.py`:

```
Traceback (most recent call last):
  File "test_matcher.py", line 6, in <module>
    matcher.match(text, best_match=True, ignore_syntax=False)
  File "/QuickUMLS/quickumls.py", line 257, in match
    matches = self._get_all_matches(ngrams)
  File "/QuickUMLS/quickumls.py", line 160, in _get_all_matches
    for start, end, ngram in ngrams:
  File "/QuickUMLS/quickumls.py", line 125, in _make_ngrams
    if self._is_valid_start_token(tok):
  File "/QuickUMLS/quickumls.py", line 79, in _is_valid_start_token
    (self._is_stop_term(tok) and tok.lemma_ not in self.negations) or
AttributeError: 'QuickUMLS' object has no attribute 'negations'
```

Thanks.

**Comment by lucasoldaini** [comment]
Thanks for reporting it. It should be fixed now!
