### ISSUE TITLE
Division by zero error when ignore_syntax=True

### ISSUE THREAD

**Issue by SnowCat29** [Georgetown-IR-Lab/QuickUMLS#37]
Not sure if this is the expected result. 
```
from quickumls import *
matcher = QuickUMLS('c:\qumls-data')
text = "The ulna has dislocated posteriorly from the trochlea of the humerus."
for p in matcher.match(text, best_match=True, ignore_syntax=True):
    for q in p:
        print(q)
```
Traceback:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\QuickUMLS\quickumls.py", line 363, in match
    matches = self._get_all_matches(ngrams)
  File "C:\QuickUMLS\quickumls.py", line 268, in _get_all_matches
    similarity_name=self.similarity_name
  File "C:\QuickUMLS\toolbox.py", line 88, in get_similarity
    return intersec / (len(X) + len(Y) - intersec)
ZeroDivisionError: division by zero
```

**Comment by soldni** [comment]
Mmmh, let me look into this — I haven’t seen this issue on my setup, so it might be something specific to your installation.

**Comment by SnowCat29** [comment]
My apologies Luca,
I had the latest release version of the files instead of the master. The commits since the latest release addressed this issue and so the master version no longer results in this error.
Ivan.

**Comment by soldni** [comment]
That's great to hear! Thank you for letting me know.
