### ISSUE TITLE
Display error in cloud instance

### ISSUE THREAD

**Issue by NarenInD** [Georgetown-IR-Lab/QuickUMLS#59]
When installing UMLS using the MetamorphoSys tool, running this command **./run_linux.sh** issues the below error

```
--------------------------------------------
Loading MetamorphoSys ...
    [Please be patient and wait for MetamorphoSys to begin]
--------------------------------------------
java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at javax.swing.JFrame.<init>(JFrame.java:233)
	at gov.nih.nlm.umls.swing.XJFrame.<init>(XJFrame.java:50)
	at gov.nih.nlm.umls.mmsys.gui.WelcomeGUI.<init>(WelcomeGUI.java:74)
	at gov.nih.nlm.umls.mmsys.gui.MetamorphoSysGuiPlugin.startApplication(MetamorphoSysGuiPlugin.java:100)
	at org.java.plugin.boot.Boot.boot(Unknown Source)
	at org.java.plugin.boot.Boot.main(Unknown Source)
java.lang.reflect.InvocationTargetException
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
	at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
	at javax.swing.SwingUtilities.invokeAndWait(SwingUtilities.java:1353)
	at gov.nih.nlm.umls.swing.SwingToolkit.reportError(SwingToolkit.java:273)
	at gov.nih.nlm.umls.mmsys.gui.MetamorphoSysGuiPlugin.startApplication(MetamorphoSysGuiPlugin.java:106)
	at org.java.plugin.boot.Boot.boot(Unknown Source)
	at org.java.plugin.boot.Boot.main(Unknown Source)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
	at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
	at java.awt.Window.<init>(Window.java:536)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1763)
	at javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1838)
	at javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1696)
	at javax.swing.JOptionPane.getWindowForComponent(JOptionPane.java:1637)
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:956)
	at javax.swing.JOptionPane.createDialog(JOptionPane.java:918)
	at gov.nih.nlm.umls.swing.SwingToolkit$1.run(SwingToolkit.java:255)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by soldni** [comment]
Hi @NarenInD! 

This is not a QuickUMLS issue; your instance doesn't have a valid X11 display (e.g. a virtual display), so the MetamorphoSys GUI cannot be launched. I recommend reviewing the documentation for how to run [MetamorphoSys is batch mode](https://www.nlm.nih.gov/research/umls/implementation_resources/community/mmsys/BatchMetaMorphoSys.html).

-Luca
