### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by vishaldeyiiest** [Georgetown-IR-Lab/QuickUMLS#62]
The readme says that the installation specifically requires UMLS MRCONSO.RRF and MRSTY.RRF. I put these files separately in a new directory and provide it as an argument `<umls_installation_path>`.
When I do `python -m quickumls.install <umls_installation_path> <destination_path>`, I get the following error:
`Traceback (most recent call last):
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls/__init__.py", line 1, in <module>
    from .core import QuickUMLS
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls/core.py", line 17, in <module>
    from . import toolbox
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls/toolbox.py", line 23, in <module>
    from quickumls_simstring import simstring
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls_simstring/simstring.py", line 28, in <module>
    _simstring = swig_import_helper()
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls_simstring/simstring.py", line 24, in swig_import_helper
    _mod = imp.load_module('_simstring', fp, pathname, description)
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /users/PAS1440/deyosu78/.conda/envs/chemprop/lib/python3.6/site-packages/quickumls_simstring/_simstring.so: undefined symbol: libiconv
`
I don't know how to resolve this? Anyone faced this issue before? Any solution?

**Comment by soldni** [comment]
Hi @vishaldeyiiest!

Could you provide me with more information about the platform and system you are trying to run QuickUMLS on? it seems like something went wrong during the installation of QuickUMLS, but I am afraid I'd need more info to figure out what exactly. 

-Luca

**Comment by alicerogier555** [comment]
Hello,
I have the same issue. I am on a jupyter server 


`jupyter --version `

"
Selected Jupyter core packages...
IPython          : 7.31.1
ipykernel        : 6.13.1
ipywidgets       : 7.7.0
jupyter_client   : 7.3.3
jupyter_core     : 4.10.0
jupyter_server   : 1.17.1
jupyterlab       : 3.4.3
nbclient         : 0.6.4
nbconvert        : 6.5.0
nbformat         : 5.4.0
notebook         : 6.4.12
qtconsole        : not installed
traitlets        : 5.2.2
"

`
pip --version
`

"
pip 22.2.2 from /opt/conda/envs/rapids/lib/python3.9/site-packages/pip (python 3.9)
"

Any solution ? 

Thanks in advance

**Comment by alicerogier555** [comment]
I resolve the problem by setting the $LD_PRELOAD variable.

**Comment by jdposada** [comment]
hi @alicerogier555,

Which path did you set on that variable? I have the same issue

**Comment by alicerogier555** [comment]
Hello @jdposada,

I set the variable with "/usr/local/lib/libiconv.so" 
Maybe you should use this command :
`
whereris libiconv
`
to see where libiconv is installed.


Hope this will work for you

**Comment by alicerogier555** [comment]
Great !
If you are working on a jupyter notebook, don't forget to set the variable also on jupyter (https://github.com/jupyter/notebook/issues/3704 )
