### ISSUE TITLE
about `nlp.add_pipe` in the demo

### ISSUE THREAD

**Issue by newbietuan** [Georgetown-IR-Lab/QuickUMLS#79]
**Describe the bug**
![1638879733](https://user-images.githubusercontent.com/48993553/145028254-5972079c-48cc-4ec9-909a-fca4879e37d9.jpg)
when i run the demo code，there something wrong about  “nlp.add_pipe(quickumls_component)”，

Traceback (most recent call last):
  File "umlsdemo.py", line 8, in <module>
    nlp.add_pipe(quickumls_component)
  File "/home/mayt/anaconda3/envs/umls/lib/python3.7/site-packages/spacy/language.py", line 769, in add_pipe
    raise ValueError(err)
ValueError: [E966] `nlp.add_pipe` now takes the string name of the registered component factory, not a callable component. Expected string, but got <quickumls.spacy_component.SpacyQuickUMLS object at 0x7f24b35e5cd0> (name: 'None').

- If you created your component with `nlp.create_pipe('name')`: remove nlp.create_pipe and call `nlp.add_pipe('name')` instead.

- If you passed in a component like `TextCategorizer()`: call `nlp.add_pipe` with the string name instead, e.g. `nlp.add_pipe('textcat')`.

- If you're using a custom component: Add the decorator `@Language.component` (for function components) or `@Language.factory` (for class components / factories) to your custom component and assign it a name, e.g. `@Language.component('your_name')`. You can then run `nlp.add_pipe('your_name')` to add it to the pipeline.

**To Reproduce**

**Environment **
 - OS: [Unbunt]
 - QuickUMLS version 1.4.0 post1
 - UMLS version  2021AB
 - spacy  3.2.0  

**Additional context**
it seems relate to spacy accroding to https://stackoverflow.com/questions/67906945/valueerror-nlp-add-pipe-now-takes-the-string-name-of-the-registered-component-f  while i still don't konw how to modify the code~~

**Comment by ygivenx** [comment]
It can be used like this. 

```python
import spacy
from spacy.language import Language
from quickumls.spacy_component import SpacyQuickUMLS

@Language.component('quickumls_component')
def quickumls_component(doc):
    return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
    

nlp.add_pipe('quickumls_component', last=True)

doc = nlp(full_rpts.iloc[0])
```

**Comment by shrimonmuke0202** [comment]
Hi everyone,
When I using this code I got the this error
`[[E090] Extension 'similarity' already exists on Span. To overwrite the existing extension, set `force=True` on `Span.set_extension`.]`

**Comment by SShmali** [comment]
@shrimonmuke0202 did you solve this problem??
[[E090] Extension 'similarity' already exists on Span. To overwrite the existing extension, set force=TrueonSpan.set_extension.]

**Comment by ysu1213** [comment]
> It can be used like this.
> 
> ```python
> import spacy
> from spacy.language import Language
> from quickumls.spacy_component import SpacyQuickUMLS
> 
> @Language.component('quickumls_component')
> def quickumls_component(doc):
>     return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
>     
> 
> nlp.add_pipe('quickumls_component', last=True)
> 
> doc = nlp(full_rpts.iloc[0])
> ```

Hi there, thank you so much for sharing a solution! I was able to get past the add_pipe error but not further. Could you explain what the line of code on doc = nlp(full_rpts.iloc[0]) does? I was trying to put into something like 
doc = nlp('Pt c/o shortness of breath, chest pain, nausea, vomiting, diarrrhea')
but that does not work. Initially I tried copy pasting your code entirely, but it returns the error saying "full_rpts" is not defined - is there some missing context here about this line of code? Thank you so much!

**Comment by ygivenx** [comment]
> > It can be used like this.
> > ```python
> > import spacy
> > from spacy.language import Language
> > from quickumls.spacy_component import SpacyQuickUMLS
> > 
> > @Language.component('quickumls_component')
> > def quickumls_component(doc):
> >     return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
> >     
> > 
> > nlp.add_pipe('quickumls_component', last=True)
> > 
> > doc = nlp(full_rpts.iloc[0])
> > ```
> 
> Hi there, thank you so much for sharing a solution! I was able to get past the add_pipe error but not further. Could you explain what the line of code on doc = nlp(full_rpts.iloc[0]) does? I was trying to put into something like doc = nlp('Pt c/o shortness of breath, chest pain, nausea, vomiting, diarrrhea') but that does not work. Initially I tried copy pasting your code entirely, but it returns the error saying "full_rpts" is not defined - is there some missing context here about this line of code? Thank you so much!

full_rpts.iloc[0] returns a string from pandas dataframe, so `doc = nlp('Pt c/o shortness of breath, chest pain, nausea, vomiting, diarrrhea')` is correct. Did you update the UMLS install location in the code below?

```python
def quickumls_component(doc):
    return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
```

**Comment by gah-bo** [comment]
> > > It can be used like this.
> > > ```python
> > > import spacy
> > > from spacy.language import Language
> > > from quickumls.spacy_component import SpacyQuickUMLS
> > > 
> > > @Language.component('quickumls_component')
> > > def quickumls_component(doc):
> > >     return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
> > >     
> > > 
> > > nlp.add_pipe('quickumls_component', last=True)
> > > 
> > > doc = nlp(full_rpts.iloc[0])
> > > ```
> > 
> > 
> > Hi there, thank you so much for sharing a solution! I was able to get past the add_pipe error but not further. Could you explain what the line of code on doc = nlp(full_rpts.iloc[0]) does? I was trying to put into something like doc = nlp('Pt c/o shortness of breath, chest pain, nausea, vomiting, diarrrhea') but that does not work. Initially I tried copy pasting your code entirely, but it returns the error saying "full_rpts" is not defined - is there some missing context here about this line of code? Thank you so much!
> 
> full_rpts.iloc[0] returns a string from pandas dataframe, so `doc = nlp('Pt c/o shortness of breath, chest pain, nausea, vomiting, diarrrhea')` is correct. Did you update the UMLS install location in the code below?
> 
> ```python
> def quickumls_component(doc):
>     return SpacyQuickUMLS(nlp, <Path to quickUmls install dir>)(doc)
> ```

Is the <Path to quickUmls install dir> supposed to be the same as quickumls_fp in 


from quickumls import QuickUMLS

matcher = QuickUMLS(quickumls_fp, overlapping_criteria, threshold,
                    similarity_name, window, accepted_semtypes)

**Comment by felipepaes** [comment]
Hi @gah-bo have you find a solution for the `Loading QuickUMLS resources from a default SAMPLE of UMLS data from here: /opt/conda/envs/python38/lib/python3.8/site-packages/resources/quickumls/QuickUMLS_SAMPLE_lowercase_POSIX_unqlite
` issue? When I try to use quickUMLS in the pipeline it uses the umls sample instead of the local instalation...
